name: Build MQ Broker Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'dev/mq/**'
      - '.github/workflows/build-mq-broker.yml'

  workflow_dispatch: 

env:
  RABBITMQ_VERSION: 3.12-alpine

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build & Push
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_NO_SUMMARY: true
      with:
        context: .
        file: dev/mq/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: RABBITMQ_VERSION=${{ env.RABBITMQ_VERSION }}
        tags: |
          ghcr.io/ietf-tools/datatracker-mq:${{ env.RABBITMQ_VERSION }}
          ghcr.io/ietf-tools/datatracker-mq:latest
